apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterFederatedTrustDomain
metadata:
  name: cluster2.demo
spec:
  trustDomain: cluster2.demo
  bundleEndpointURL: https://172.16.17.3:8443 #replace with ip of spire server endpoint on cluster 2
  bundleEndpointProfile:
    type: https_spiffe
    endpointSPIFFEID: spiffe://cluster2.demo/spire/server
  trustDomainBundle: |- #add trust bundle keys from cluster 2
    {
      
    }
